# Generated by Django 3.2.9 on 2021-11-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('camping_tools', 'camping_tools'), ('camping_ground', 'camping_ground'), ('free', 'free')], default='camping_tools', max_length=20)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
