# Generated by Django 3.2.5 on 2021-11-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpost',
            name='category',
            field=models.CharField(choices=[('camping_tools', 'camping_tools'), ('camping_ground', 'camping_ground'), ('free', 'free')], default='camping_tools', max_length=20),
        ),
    ]
