# Generated by Django 3.2.9 on 2021-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/'),
        ),
        migrations.AlterField(
            model_name='bulletinpost',
            name='body',
            field=models.TextField(),
        ),
    ]
