# Generated by Django 3.2.5 on 2021-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping_ground', '0003_remove_campingground_desc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='campingground',
            name='desc_img',
            field=models.ImageField(default='static/lantern.jpg', upload_to=''),
        ),
    ]
