# Generated by Django 3.2.9 on 2021-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampingTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=10)),
                ('rental_fee', models.IntegerField(default=20000)),
                ('body', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('tent', 'tent'), ('grill', 'grill'), ('table', 'table'), ('lantern', 'lantern'), ('firewood', 'firewood')], default='tent', max_length=20)),
                ('image', models.ImageField(default='static/lantern.jpg', upload_to='')),
            ],
        ),
    ]
