# Generated by Django 3.2.9 on 2021-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping_tools', '0002_orderlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campingtools',
            old_name='rental_fee',
            new_name='rental_price',
        ),
        migrations.AddField(
            model_name='campingtools',
            name='price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='campingtools',
            name='body',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='campingtools',
            name='category',
            field=models.CharField(choices=[('tent', 'tent'), ('grill', 'grill'), ('table', 'table'), ('lantern', 'lantern'), ('firewood', 'firewood')], default='lentern', max_length=20),
        ),
    ]
