# Generated by Django 3.2.9 on 2021-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AddField(
            model_name='member',
            name='people_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
